### ISSUE TITLE
Add page numbering

### ISSUE THREAD

**Issue by davidmihalyi** [nstrayer/datadrivencv#13]
Page numbers would be useful addition especially to PDF version.

**Comment by nstrayer** [comment]
A great point! I believe that this is not too hard with paged.js.

**Comment by nstrayer** [comment]
[Here's the paged.js docs on this](https://www.pagedjs.org/documentation/07-generated-content-in-margin-boxes/#page-counter). 

```css
@page {
  @bottom-left {
        content: counter(page);
  }
}
```
