### ISSUE TITLE
Change date format

### ISSUE THREAD

**Issue by vpara** [nstrayer/datadrivencv#45]
Hi Nick, could you help me to print the dates on the resume to GMT+1 in Dutch/Netherlands?

Thanks in advance!

Love the datadriven cv!

Gr. Vinood

**Comment by MaraAlexeev** [comment]
Could you expand your question? The template CV should have something similar to this in the header (this is from my own edited version):

```
---
title: "Mara Alexeev's CV"
author: Mara Alexeev
date: "`r Sys.Date()`"
params:
  pdf_mode:
    value: true
output:
  pagedown::html_resume:
    css: ['dd_cv.css', 'resume']
    self_contained: true

---
```
The date variable `r Sys.Date()` should pull in your local system's current date.
